import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      colorScheme: colorScheme,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary.withOpacity(1),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              5,
            ),
          ),
          shadowColor: colorScheme.primary,
          elevation: 10,
        ),
      ),
      textTheme: TextTheme(
        bodySmall: TextStyle(
          color: appTheme.blueGray300,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        labelMedium: TextStyle(
          color: appTheme.pink300,
          fontSize: getFontSize(
            10,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
      ),
      visualDensity: VisualDensity.standard,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    onPrimary: Color(0X87223263),
    shadow: Color(0X87223263),
    onPrimaryContainer: Color(0X87FFFFFF),
    onTertiary: Color(0X87FFFFFF),
    scrim: Color(0X87223263),
    primaryContainer: Color(0X87223263),
    tertiaryContainer: Color(0X3D40BFFF),
    secondaryContainer: Color(0X3D40BFFF),
    error: Color(0X87223263),
    onErrorContainer: Color(0X87223263),
    outline: Color(0X87223263),
    onSurfaceVariant: Color(0X87223263),
    onBackground: Color(0X87FFFFFF),
    outlineVariant: Color(0X87223263),
    errorContainer: Color(0X3D40BFFF),
    onSurface: Color(0X87FFFFFF),
    onError: Color(0X87FFFFFF),
    surface: Color(0X87223263),
    onInverseSurface: Color(0X87FFFFFF),
    onSecondaryContainer: Color(0X87223263),
    tertiary: Color(0X87223263),
    surfaceTint: Color(0X87223263),
    onTertiaryContainer: Color(0X87223263),
    surfaceVariant: Color(0X3D40BFFF),
    inversePrimary: Color(0X87223263),
    secondary: Color(0X87223263),
    inverseSurface: Color(0X87223263),
    background: Color(0X87223263),
    onSecondary: Color(0X87FFFFFF),
    primary: Color(0X3D40BFFF),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  Color get primaryVariant => Color(0X87223263);
  Color get secondaryVariant => Color(0X3D40BFFF);
  Color get indigoA200 => Color(0XFF5B61F4);
  Color get gray400 => Color(0XFFC4C4C4);
  Color get blueA200 => Color(0XFF4091FF);
  Color get lightBlue600 => Color(0XFF039BE5);
  Color get yellow700 => Color(0XFFFFC732);
  Color get blueGray300 => Color(0XFF9098B1);
  Color get pink300 => Color(0XFFFB7181);
  Color get blue50 => Color(0XFFEAEFFF);
  Color get amber500 => Color(0XFFFFC107);
  Color get blueGray400 => Color(0XFF888888);
  Color get black900 => Color(0XFF000000);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
